development:
  adapter: postgresql
  encoding: unicode
  database: database_name_development
  pool: 5
  host: localhost
  username: user
  password: billtracker

test:
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  pool: 5
  username: user
  password: billtracker

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 